version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "MyPhotoProcessor"
        Alias: "Prod"
        CurrentVersion: "1"
        TargetVersion: "3"