version: 0.0
os: linux
files:
  - source: assignment-1-2-4
    destination: /home/ec2-user/server
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 120
