version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build started on `date`
      - cd assignment-1-2-4
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/my-app-0.1-SNAPSHOT.jar
  discard-paths: yes
  base-directory: 'assignment-1-2-4'