version: '2.0'
services:
  frontend:
    build: frontend/.
    ports:
    - "20080:80"
    depends_on: 
        - "backend"
  backend:
    container_name: "cddb_backend"
    build: backend/.
    depends_on: 
        - "database"
  database:
    container_name: "cddb_mysql"
    image: mysql:5.6
    environment: 
        - MYSQL_ROOT_PASSWORD=quintor_pw
        - MYSQL_DATABASE=cddb_quintor
        - MYSQL_USER=cddb_quintor
        - MYSQL_PASSWORD=quintor_pw